baseurl = "https://intuitive-robots.github.io/ml-cur/"
DefaultContentLanguage = "en"
title = "MP3: Movement Primitive-Based (Re-)Planning Policies"
theme = ["beautifulhugo"]
#pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "MP3: Movement Pritimitve-Based (Re-)Planning Policies" # Set a different text for the header on the home page
  subtitle = " "
  #mainSections = ["post","posts"]
  logo = "img/IRL_Logo_Icon_blue.svg" # Expecting square dimensions
  favicon = "img/IRL_Logo_Icon_blue.svg"
  dateFormat = "January 2, 2006"
  commit = false
  #rss = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Hongyi Zhou"
#  website = "yourwebsite.com"
  email = "hongyi.zhou@kit.edu"
#  facebook = "username"
  github = " "
  pdf = " "


[[menu.main]]
    name = "Paper (Coming Soon)"
    url = " "
    weight = 1

[[menu.main]]
    name = "Code (Coming Soon)"
    url = " "
    weight = 3
